---
title: "| Ecoinformática: nuevo grupo de trabajo de la Asociación Española de Ecología Terrestre \n| Ecoinformatics: new working group within the Spanish Terrestrial Ecology Association\n"
  
author: Francisco Rodríguez-Sánchez^1^, Antonio Jesús Pérez-Luque^2^, Ignasi Bartomeus^1^, Sara Varela^3^
  
output:
  word_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 7.5
    highlight: null
    reference_docx: Ecosistemas_template.docx
    
csl: ecosistemas.csl
---


> (1) Departamento de Ecología Integrativa, Estación Biológica de Doñana (EBD-CSIC), Consejo Superior de Investigaciones Científicas, Avda. Américo Vespucio s/n, E-41092 Sevilla, España.

> (2) Laboratorio de Ecología (iEcolab), Instituto Interuniversitario Sistema Tierra (CEAMA), Universidad de Granada, Avda. del Mediterráneo s/n, Granada 18006, España.

> (3) Departamento de Ciencias de la Vida, Facultad de Biología, Ciencias Ambientales y Química, Universidad de Alcalá, Campus Universitario. Ctra. Madrid-Barcelona, Km. 33,600, 28805 Alcalá de Henares, Madrid, España.

> Dirección de contacto: [ecoinf.aeet@gmail.com]


La ecología actual, como otras disciplinas científicas, tiene casi siempre un componente importante de computación. Desde un sencillo análisis estadístico de datos hasta la realización de simulaciones estocásticas complejas, casi todos los ecólogos necesitan interaccionar en mayor o menor medida con una computadora. Sin embargo, hasta ahora la formación de los ecólogos en aspectos tales como el manejo de bases de datos, análisis de datos, modelización, programación, etc. ha sido escasa. Esto no sólo acarrea retrasos y problemas en la ejecución de los proyectos de investigación, sino que también limita el potencial y alcance de los mismos. 

Motivados por esta situación, se acaba de crear dentro de la Asociación Española de Ecología Terrestre (AEET) un nuevo grupo de trabajo sobre Ecoinformática (http://www.aeet.org/EcoInformatica_383_p.htm). Este grupo de trabajo pretende fomentar el intercambio de experiencias y conocimientos sobre cualquier aspecto relacionado con la ecoinformática (en sentido amplio, incluyendo manejo y análisis de datos, simulaciones, modelización, y programación), además de contribuir a la formación de los nuevos ecólogos en buenas prácticas y técnicas de computación que les permitan desarrollar al máximo sus proyectos de investigación. Entre los objetivos del grupo también se encuentra el de promover la ciencia abierta y reproducible. 

Para contribuir a estos objetivos se prevé la organización de cursos y talleres así como simposios relacionados con la ecoinformática en los congresos de la AEET. Para el próximo congreso AEET-MEDECOS ya está aceptado un simposio sobre 'Ecoinformatics: data science brings new avenues for ecology'. Además se ha creado una cuenta de twitter (@ecoinf_aeet) y una lista de correo (https://groups.google.com/forum/#!forum/ecoinformatica_aeet) para compartir conocimientos y organizar nuevas actividades. Además existe una cuenta de correo específica para contactar con los coordinadores del grupo de trabajo: ecoinf.aeet@gmail.com

Desde su creación hace tan solo unos meses, el grupo de trabajo ha tenido muy buena acogida. Esperamos que cumpla una función útil para el avance de la ecología en las próximas décadas.













